# Generated by Django 3.2 on 2021-10-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_group_groupowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.userprofile'),
        ),
    ]
