# Generated by Django 3.2 on 2021-11-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_customquestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.query_utils.DeferredAttribute object at 0x7f9eeb2e3fa0>/'),
        ),
    ]
